### ISSUE TITLE
Problem on install.

### ISSUE THREAD

**Issue by ipppinto** [2amigos/yii2-ckeditor-widget#29] opened 2015-03-23 16:24 UTC
I have always this error:

# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/jquery (2.1.3)
Reading bower.json of bower-asset/jquery.inputmask (3.1.61)
Reading bower.json of bower-asset/punycode (v1.3.2)
Reading bower.json of bower-asset/yii2-pjax (v2.0.4)
Reading bower.json of bower-asset/jquery-ui (1.11.4)
Reading bower.json of bower-asset/bootstrap (v3.3.4)
Reading bower.json of bower-asset/typeahead.js (v0.10.5)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-ckeditor-widget 1.0.2 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
    - 2amigos/yii2-ckeditor-widget 1.0.1 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
    - 2amigos/yii2-ckeditor-widget 1.0.0 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
    - Installation request for 2amigos/yii2-ckeditor-widget ~1.0 -> satisfiable by 2amigos/yii2-ckeditor-widget[1.0.0, 1.0.1, 1.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

My composer:
```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Application Template",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "mdmsoft/yii2-admin": "*",
        "kartik-v/yii2-widgets": "*",
        "2amigos/yii2-ckeditor-widget" : "~1.0"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by tonydspaniard** [comment] 2015-03-23 17:13
Strange... have you done composer self-update? https://packagist.org/packages/ckeditor/ckeditor#dev-full/stable

**Comment by tonydspaniard** [comment] 2015-03-23 17:14
If the problem persist, I will consider modifying the resource from 'composer' to 'bower'

**Comment by ipppinto** [comment] 2015-03-23 17:20
If I change my composer "2amigos/yii2-ckeditor-widget" : "~1.0" to "2amigos/yii2-ckeditor-widget" : "*" I don't have errors but the version of widget isn't 1.0.2.

Have I to change "minimum-stability": "stable" to another config?

**Comment by ipppinto** [comment] 2015-03-23 17:24
I have add ckeditor to composer?

"minimum-stability": "stable",
"require": {
"php": ">=5.4.0",
"yiisoft/yii2": "",
"yiisoft/yii2-bootstrap": "",
"yiisoft/yii2-swiftmailer": "",
"mdmsoft/yii2-admin": "",
"kartik-v/yii2-widgets": "",
"2amigos/yii2-ckeditor-widget" : "~1.0"

**Comment by tonydspaniard** [comment] 2015-03-23 17:25
You need to put versions on the rest of the libraries

**Comment by ipppinto** [comment] 2015-03-23 17:28
Sorry..

Where I do this?

**Comment by tonydspaniard** [comment] 2015-03-23 17:29
```php 
"yiisoft/yii2": "",
"yiisoft/yii2-bootstrap": "", <--- ?
"yiisoft/yii2-swiftmailer": "", <--- ?
"mdmsoft/yii2-admin": "", <--- ?
"kartik-v/yii2-widgets": "", <--- ?
```

**Comment by ipppinto** [comment] 2015-03-23 17:33
I put this and install ok:

    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "mdmsoft/yii2-admin": "*",
        "kartik-v/yii2-widgets": "*",
        "ckeditor/ckeditor": "dev-full/stable", <----
        "2amigos/yii2-ckeditor-widget" : "~1.0"

But I will put the versions on my libraries.

Thank you.

**Comment by tonydspaniard** [comment] 2015-03-23 17:34
This doesn't need to be this: 

```php 
"require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "*",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-swiftmailer": "*",
    "mdmsoft/yii2-admin": "*",
    "kartik-v/yii2-widgets": "*",
    "ckeditor/ckeditor": "dev-full/stable", <---- This you don't need, is installed by yii2-ckeditor-widget
    "2amigos/yii2-ckeditor-widget" : "~1.0"
```

**Comment by ipppinto** [comment] 2015-03-23 17:40
But with this I install the the widget and without I can't install.

I don't know why...

**Comment by ipppinto** [comment] 2015-03-23 17:42
My composer now:

    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.3",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "mdmsoft/yii2-admin": "~1.0",
        "kartik-v/yii2-widgets": "*",
        "2amigos/yii2-ckeditor-widget" : "~1.0"
    },

If I update my composer I have this error:

# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/jquery (2.1.3)
Reading bower.json of bower-asset/jquery.inputmask (3.1.61)
Reading bower.json of bower-asset/punycode (v1.3.2)
Reading bower.json of bower-asset/yii2-pjax (v2.0.4)
Reading bower.json of bower-asset/jquery-ui (1.11.4)
Reading bower.json of bower-asset/bootstrap (v3.3.4)
Reading bower.json of bower-asset/typeahead.js (v0.10.5)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-ckeditor-widget 1.0.2 requires ckeditor/ckeditor dev-full/stable -> satisfiable by ckeditor/ckeditor[dev-full/stable].
    - 2amigos/yii2-ckeditor-widget 1.0.0 requires ckeditor/ckeditor dev-full/stable -> satisfiable by ckeditor/ckeditor[dev-full/stable].
    - 2amigos/yii2-ckeditor-widget 1.0.1 requires ckeditor/ckeditor dev-full/stable -> satisfiable by ckeditor/ckeditor[dev-full/stable].
    - 2amigos/yii2-ckeditor-widget 1.0.2 requires ckeditor/ckeditor dev-full/stable -> satisfiable by ckeditor/ckeditor[dev-full/stable].
    - Removal request for ckeditor/ckeditor == dev-full/stable
    - Installation request for 2amigos/yii2-ckeditor-widget ~1.0 -> satisfiable by 2amigos/yii2-ckeditor-widget[1.0.0, 1.0.1, 1.0.2].

**Comment by ipppinto** [comment] 2015-03-23 17:43
If I change to:

    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "mdmsoft/yii2-admin": "*",
        "kartik-v/yii2-widgets": "*",
        "ckeditor/ckeditor": "dev-full/stable",
        "2amigos/yii2-ckeditor-widget" : "~1.0"

Install ok.

**Comment by ipppinto** [comment] 2015-03-23 17:58
I put version on my libraries I if I don't have this "ckeditor/ckeditor": "dev-full/stable" I have always the same error.

**Comment by ipppinto** [comment] 2015-03-25 14:37
Hi,

Any solution to this problem?

Thank you.

**Comment by tonydspaniard** [comment] 2015-03-25 19:33
@ipppinto I believe there is an issue with the version used on packagist. I am thinking to modify the requirement and use bower plugin instead.

**Comment by trejder** [comment] 2015-04-09 08:40
I have (had) exactly the same problem. Executing `composer self-update` changes nothing (Composer version up-to-date). Problem is caused by installing package with:

    composer require 2amigos/yii2-ckeditor-widget:~1.0

Which ends with:

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - 2amigos/yii2-ckeditor-widget 1.0.2 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
        - 2amigos/yii2-ckeditor-widget 1.0.1 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
        - 2amigos/yii2-ckeditor-widget 1.0.0 requires ckeditor/ckeditor dev-full/stable -> no matching package found.
        - Installation request for 2amigos/yii2-ckeditor-widget ~1.0 -> satisfiable by 2amigos/yii2-ckeditor-widget[1.0.0, 1.0.1, 1.0.2].

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
    or more details.

    Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

    Installation failed, reverting ./composer.json to its original content.

Solution is to Install package with:

    composer require 2amigos/yii2-ckeditor-widget:*

or add `"2amigos/yii2-ckeditor-widget" : "*"` to `require` section and execute `composer update`. Using unbound versions (`*`) in Composer is not recommended, but this is the only workaround, that I found for this problem.

**Comment by tonydspaniard** [comment] 2015-04-09 14:48
@trejder will fix it asap

**Comment by creocoder** [comment] 2015-04-11 10:06
Fixed by new release.

**Closed** 2015-04-11 10:11 UTC
