### ISSUE TITLE
After last composer update, the full version not render...

### ISSUE THREAD

**Issue by rafaelwithoeft** [2amigos/yii2-ckeditor-widget#33] opened 2015-04-13 20:06 UTC
After last update, the full version of ckeditor not render, only the basic or standart... why? :/

 __composer.json__

    "2amigos/yii2-ckeditor-widget" : "~1.0"

__code__

    echo $form->field($modelCabecalho, 'valor', ['template' => '{input}{hint}{error}'])->widget(CKEditor::className(), [
        'options' => ['rows' => 3],
        'preset' => 'full'
    ]);

**Comment by tonydspaniard** [comment] 2015-04-14 21:55
The problem is the latest update: https://github.com/2amigos/yii2-ckeditor-widget/commit/d2e4c965a4524e1572d516f1995bac1130457cc1#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R30 

@creocoder we need to full version of it

**Comment by osnwach** [comment] 2015-04-28 17:04
CKeditor not showing on my form.
I used this code: 
<?= $form->field($model, 'comment')->widget(\dosamigos\ckeditor\CKEditor::className(),[
'preset'=>'full',
]) ?>

But I dont see the CKeditor, when I preview in Browser. Please why is it so ?

**Comment by tonydspaniard** [comment] 2015-04-29 02:04
Will fix it tomorrow guys sorry

**Comment by tonydspaniard** [comment] 2015-04-29 02:04
We made a mistake... Apologies

**Comment by creocoder** [comment] 2015-04-30 12:23
Fixed by 1.0.4 release

**Closed by creocoder** 2015-04-30 12:23 UTC
Labels: bug
